# Generated by Django 5.2.6 on 2025-09-29 00:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='pdf',
            field=models.FileField(upload_to='libros/archivos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'gif'])], verbose_name='Archivo (PDF o Imagen)'),
        ),
    ]
